### ISSUE TITLE
Installation page is missing resources

### ISSUE THREAD

**Issue by gwmensink** [CastleCSS/castlecss-docs#1]
When opening the following page, Chrome reports that files are missing:

[http://www.castlecss.com/installation.html](http://www.castlecss.com/installation.html)

![castlecss](https://cloud.githubusercontent.com/assets/10388905/17837736/8ef2aca8-67bb-11e6-8699-e979c33a75fb.png)

**Comment by dariusrosendahl** [comment]
Just fixed this in the repo and on castlecss.com. Thanks!
