### ISSUE TITLE
classes .as-space-around and .as-space-between don't exist

### ISSUE THREAD

**Issue by pascalalferink** [CastleCSS/castlecss-docs#16]
In the documentation , the classes **as-space-around** and **as-space-between** are mentioned, but these values are not valid for this property. 

Therefore these should be removed from the documentation

**Comment by pascalalferink** [comment]
pull-request has been made for this issue: https://github.com/CastleCSS/castlecss-docs/pull/17

**Comment by dariusrosendahl** [comment]
Merged
